let x = 1 in
(
  (
    try 
    (
      try throw(11)
      catch (exc) print(exc)
      finally (throw(3 * x); x = 55)
    )
    finally print(x)
  );
  print(x);
  x == 1
)
